version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g typescript
      - npm install -g @nestjs/cli
  pre_build:
    commands:
      - echo Installing source dependencies
      - npm ci && npm cache clean --force
      # upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  build:
    commands:
      - echo Build started
      #- npm run build
      - tsc -p tsconfig.json
  post_build:
    commands:
      # - node ./dist/main.js
artifacts:
  files:
    - 'dist/**/*'
    - package.json
    - package-lock.json
    - tsconfig.json
    - 'node_modules/**/*'