version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm install -g typescript @nestjs/cli
      - npm ci && npm cache clean --force
      # upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  build:
    commands:
      - echo Build started
      - npm run build
      #- tsc -p tsconfig.json
  post_build:
    commands:
      # - node ./dist/main.js